package info.technikality.nzhighway.LRMS;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.1.0
//
// Created by Quasar Development at 30-08-2014
//
//---------------------------------------------------



public interface LQJIServiceEvents
{
    public void Starting();
    public void Completed(LQJOperationResult result);
}
