

package info.technikality.nzhighway.LRMS;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.1.0
//
// Created by Quasar Development at 30-08-2014
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class LQJLrmsPortBinding
{
    interface LQJIWcfMethod
    {
        LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://lrms.highwayinfo.govt.nz:80/lrms/service/v4/LrmsService";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    LQJIServiceEvents callback;
    public LQJLrmsPortBinding(){}

    public LQJLrmsPortBinding (LQJIServiceEvents callback)
    {
        this.callback = callback;
    }
    public LQJLrmsPortBinding(LQJIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public LQJLrmsPortBinding(LQJIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                return new HttpsTransportSE(uri.getHost(), uri.getPort(), uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected LQJExtendedSoapSerializationEnvelope createEnvelope()
    {
        LQJExtendedSoapSerializationEnvelope envelope= new LQJExtendedSoapSerializationEnvelope();
        return envelope;
    }
    
    protected void sendRequest(String methodName,LQJExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport) throws java.lang.Exception
    {
        transport.call(methodName, envelope,httpHeaders);
    }


    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,LQJExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }
    
    public LQJlrmsPoint locatePointFromRp(final String rp,final Integer srid ) throws java.lang.Exception
    {
        return (LQJlrmsPoint)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://argonautltd.co.nz/lrms/4", "locatePointFromRp");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="rp";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(rp!=null?rp:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="srid";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(srid);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJlrmsPoint)getResult(LQJlrmsPoint.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask locatePointFromRpAsync(final String rp,final Integer srid)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJlrmsPoint>() {
            public LQJlrmsPoint Func() throws java.lang.Exception {
                return locatePointFromRp( rp,srid);
            }
        });
    }
    
    public LQJlrmsPoint locatePointFromSpatial(final Double x,final Double y,final Double widthMetres,final Double heightMetres,final Integer srid ) throws java.lang.Exception
    {
        return (LQJlrmsPoint)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://argonautltd.co.nz/lrms/4", "locatePointFromSpatial");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="x";
                __info.type=Double.class;
                __info.setValue(x);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="y";
                __info.type=Double.class;
                __info.setValue(y);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="widthMetres";
                __info.type=Double.class;
                __info.setValue(widthMetres);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="heightMetres";
                __info.type=Double.class;
                __info.setValue(heightMetres);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="srid";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(srid);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJlrmsPoint)getResult(LQJlrmsPoint.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask locatePointFromSpatialAsync(final Double x,final Double y,final Double widthMetres,final Double heightMetres,final Integer srid)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJlrmsPoint>() {
            public LQJlrmsPoint Func() throws java.lang.Exception {
                return locatePointFromSpatial( x,y,widthMetres,heightMetres,srid);
            }
        });
    }
    
    public LQJlrmsPoint locatePointAlongRs(final String sh,final Integer rs,final Double displacementMetres,final String direction,final Integer srid ) throws java.lang.Exception
    {
        return (LQJlrmsPoint)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://argonautltd.co.nz/lrms/4", "locatePointAlongRs");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="sh";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(sh!=null?sh:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="rs";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(rs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="displacementMetres";
                __info.type=Double.class;
                __info.setValue(displacementMetres);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="direction";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(direction!=null?direction:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="srid";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(srid);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJlrmsPoint)getResult(LQJlrmsPoint.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask locatePointAlongRsAsync(final String sh,final Integer rs,final Double displacementMetres,final String direction,final Integer srid)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJlrmsPoint>() {
            public LQJlrmsPoint Func() throws java.lang.Exception {
                return locatePointAlongRs( sh,rs,displacementMetres,direction,srid);
            }
        });
    }
    
    public LQJlrmsLinear locateLinear(final LQJlrmsPoint start,final LQJlrmsPoint end,final String direction,final Integer srid ) throws java.lang.Exception
    {
        return (LQJlrmsLinear)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("","start",new LQJlrmsPoint().getClass());
                __envelope.addMapping("","end",new LQJlrmsPoint().getClass());
                SoapObject __soapReq = new SoapObject("http://argonautltd.co.nz/lrms/4", "locateLinear");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="start";
                __info.type=LQJlrmsPoint.class;
                __info.setValue(start!=null?start:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="end";
                __info.type=LQJlrmsPoint.class;
                __info.setValue(end!=null?end:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="direction";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(direction!=null?direction:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="srid";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(srid);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJlrmsLinear)getResult(LQJlrmsLinear.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask locateLinearAsync(final LQJlrmsPoint start,final LQJlrmsPoint end,final String direction,final Integer srid)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJlrmsLinear>() {
            public LQJlrmsLinear Func() throws java.lang.Exception {
                return locateLinear( start,end,direction,srid);
            }
        });
    }
    
    public LQJhighwayResponse highway(final String sh,final Integer srid ) throws java.lang.Exception
    {
        return (LQJhighwayResponse)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://argonautltd.co.nz/lrms/4", "highway");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="sh";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(sh!=null?sh:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="srid";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(srid);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJhighwayResponse)getResult(LQJhighwayResponse.class,__result,"highwayResponse",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask highwayAsync(final String sh,final Integer srid)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJhighwayResponse>() {
            public LQJhighwayResponse Func() throws java.lang.Exception {
                return highway( sh,srid);
            }
        });
    }
    
    public LQJreferenceStationsResponse referenceStations(final String sh,final Integer fromRs,final Integer toRs,final Integer srid ) throws java.lang.Exception
    {
        return (LQJreferenceStationsResponse)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://argonautltd.co.nz/lrms/4", "referenceStations");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="sh";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(sh!=null?sh:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="fromRs";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(fromRs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="toRs";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(toRs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="srid";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(srid);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJreferenceStationsResponse)getResult(LQJreferenceStationsResponse.class,__result,"referenceStationsResponse",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask referenceStationsAsync(final String sh,final Integer fromRs,final Integer toRs,final Integer srid)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJreferenceStationsResponse>() {
            public LQJreferenceStationsResponse Func() throws java.lang.Exception {
                return referenceStations( sh,fromRs,toRs,srid);
            }
        });
    }
    
    public LQJlocateMultipleResponse locateMultiple(final LQJlocateMultiple locateMultiple ) throws java.lang.Exception
    {
        return (LQJlocateMultipleResponse)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://argonautltd.co.nz/lrms/4","locateMultiple",new LQJlocateMultiple().getClass());
                __envelope.setOutputSoapObject(locateMultiple);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJlocateMultipleResponse)getResult(LQJlocateMultipleResponse.class,__result,"locateMultipleResponse",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask locateMultipleAsync(final LQJlocateMultiple locateMultiple)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJlocateMultipleResponse>() {
            public LQJlocateMultipleResponse Func() throws java.lang.Exception {
                return locateMultiple( locateMultiple);
            }
        });
    }
    
    public LQJlocateMultipleAlongRoadResponse locateMultipleAlongRoad(final LQJlocateMultipleAlongRoad locateMultipleAlongRoad ) throws java.lang.Exception
    {
        return (LQJlocateMultipleAlongRoadResponse)execute(new LQJIWcfMethod()
        {
            @Override
            public LQJExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                LQJExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://argonautltd.co.nz/lrms/4","locateMultipleAlongRoad",new LQJlocateMultipleAlongRoad().getClass());
                __envelope.setOutputSoapObject(locateMultipleAlongRoad);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(LQJExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (LQJlocateMultipleAlongRoadResponse)getResult(LQJlocateMultipleAlongRoadResponse.class,__result,"locateMultipleAlongRoadResponse",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask locateMultipleAlongRoadAsync(final LQJlocateMultipleAlongRoad locateMultipleAlongRoad)
    {
        return executeAsync(new LQJFunctions.IFunc< LQJlocateMultipleAlongRoadResponse>() {
            public LQJlocateMultipleAlongRoadResponse Func() throws java.lang.Exception {
                return locateMultipleAlongRoad( locateMultipleAlongRoad);
            }
        });
    }
    
    public String findOffsetKmBetweenPoints(final String start,final String end,final String srid,final String arg3 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask findOffsetKmBetweenPointsAsync(final String start,final String end,final String srid,final String arg3)
    {
        return executeAsync(new LQJFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return findOffsetKmBetweenPoints( start,end,srid,arg3);
            }
        });
    }
    
    public String locateLinearParts(final String start,final String end,final String direction,final String srid ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask locateLinearPartsAsync(final String start,final String end,final String direction,final String srid)
    {
        return executeAsync(new LQJFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return locateLinearParts( start,end,direction,srid);
            }
        });
    }
    
    public String locatePointOnHighwayFromSpatial(final String x,final String y,final String width,final String height,final String sh,final String srid ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask locatePointOnHighwayFromSpatialAsync(final String x,final String y,final String width,final String height,final String sh,final String srid)
    {
        return executeAsync(new LQJFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return locatePointOnHighwayFromSpatial( x,y,width,height,sh,srid);
            }
        });
    }
    
    public String locatePointOnHighwayDirectionFromSpatial(final String x,final String y,final String width,final String height,final String sh,final String direction,final String srid ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask locatePointOnHighwayDirectionFromSpatialAsync(final String x,final String y,final String width,final String height,final String sh,final String direction,final String srid)
    {
        return executeAsync(new LQJFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return locatePointOnHighwayDirectionFromSpatial( x,y,width,height,sh,direction,srid);
            }
        });
    }
    
    public String transformMultipleGeoms(final String transformMultipleGeoms ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask transformMultipleGeomsAsync(final String transformMultipleGeoms)
    {
        return executeAsync(new LQJFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return transformMultipleGeoms( transformMultipleGeoms);
            }
        });
    }
    
    public String transformGeom(final String wktGeom,final String srcSrid,final String destSrid ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask transformGeomAsync(final String wktGeom,final String srcSrid,final String destSrid)
    {
        return executeAsync(new LQJFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return transformGeom( wktGeom,srcSrid,destSrid);
            }
        });
    }
    
    public String transformPoint(final String x,final String y,final String srcSrid,final String destSrid ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask transformPointAsync(final String x,final String y,final String srcSrid,final String destSrid)
    {
        return executeAsync(new LQJFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return transformPoint( x,y,srcSrid,destSrid);
            }
        });
    }
    protected java.lang.Object execute(LQJIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        LQJExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    protected < T> android.os.AsyncTask  executeAsync(final LQJFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, LQJOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected LQJOperationResult< T> doInBackground(Void... params) {
                LQJOperationResult< T> result = new LQJOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(LQJOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
   
      

    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,LQJExtendedSoapSerializationEnvelope envelope)
    {
        return new java.lang.Exception(fault.faultstring);
    }
}


